version: '3'
services:
  db:
    container_name: EmpresaBD
    image: mariadb
    environment:
      MARIADB_USER: Negocios
      MARIADB_PASSWORD: Negociospsw
      MARIADB_DATABASE: NegociosDB
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"

      